### ISSUE TITLE
pbicli login with service-principal is not working

### ISSUE THREAD

**Issue by rohank-proarch** [powerbi-cli/powerbi-cli#22]
I am trying to create workspace from Azure DevOps agent so tried to login using service principal of the service connection. But it is not able to login, i also tried using pbicli login --azurecli after logging in using my user credentials and then it worked.
It is not working using service principal. The service connection is a Global Admin also it has all the delegated permissions of Power BI Service. Please help.

**Comment by sagarkul** [comment]
I am having the same issue.


`pbicli login --service-principal --principal $SPID --secret "$SECRET" --tenant "$TENANT" --verbose
`
below is the verbose response 
```
Login in to Power BI and retrieve an access token
Check if stored token is not expired

```

I am using bash here.

**Comment by liprec** [comment]
Thanks for the issues and please can you try the following:
- make sure that the `secret` doesn't contain spaces
- use the variables *without* quotes as these are considered part of the secret/tenant

**Comment by rohank-proarch** [comment]
Ok will try without quotes

**Comment by rohank-proarch** [comment]
Still did not work. Secret does not have spaces and have removed quotes as well

**Comment by liprec** [comment]
Can you validate that the SP does at least have the `Workspace.ReadWrite.All` API permissions assigned to create a workspace?

And alternative you can use the Azure CLI task Azure DevOps task with a Resource Connection using your SP and then use `pbicli login --azurecli` to login using the SP of the Resource Connection

**Comment by rohank-proarch** [comment]
Yes the SP have all the permissions.
Yes i am using Azure CLI task and in that bash script file i tried calling pbicli login --azurecli and as well as pbicli login --service-principal. Both did not work

![image](https://user-images.githubusercontent.com/60872102/110347839-06d40380-8057-11eb-86a0-d60a5cc687af.png)

**Comment by liprec** [comment]
Thanks, but I do not have any idea what can cause this issue. Below is the YAML script that I am using as demo to login via the Azure CLI task. Maybe it can help you in identifying the issue as this is working for me

```
name: 01. basics

trigger: none

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Npm@1
  displayName: install pbicli
  inputs:
    command: custom
    customCommand: |
      i @powerbi-cli/powerbi-cli
- task: AzureCLI@2
  displayName: run pbicli inline script
  inputs:
    azureSubscription: 'Azure / Power BI CLI'
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: |
      # Expand PATH to contain the home directory of 'pbicli'; needed because 'pbicli' is installed locally
      export PATH=$(Agent.WorkFolder)/node_modules/.bin:$PATH
      
      # Check the pbicli version
      pbicli version

      # Login via the AzureCLI
      pbicli login --azurecli

      # Retrieve names of the workspaces
      pbicli workspace list --query "[*].{name:name}"
```
